
author:
    - name: Jamiel Dannouf
      email: dannoufja@vcu.edu

date: last-modified

format:
    html:
        theme: darkly
        toc: true
        embed-resources: true
        code-copy: true

execute:
  echo: true
  eval: true
  cache: false
